### ISSUE TITLE
MinGW support for libcadical

### ISSUE THREAD

**Issue by Coder-256** [arminbiere/cadical#15]
I have implemented [support for `libcadical` in MinGW](https://github.com/arminbiere/cadical/compare/master...Coder-256:mingw?w=1) and due to the contributing guidelines have decided to open an issue here before opening a pull request. I am willing to release my changes under CC0 if that would help.

Here are the changes:

- Only build `signal.cpp` for the app targets (not needed for `libcadical`, and fails to build on MinGW)
- Make sure that object files are outputted into the correct place using `-o $@`
- On MinGW, disable process time/memory statistics

**Comment by arminbiere** [comment]
This is anyhow on my TODO list (but with low priority).

**Comment by deiruch** [comment]
For those interested, I published Win32 x64 binaries under https://github.com/deiruch/cadical/releases/tag/rel-1.2.1b

This port compiles with Visual Studio 2019, without MinGW dependencies. Everything appears to work, except the time limit.

**Comment by arminbiere** [comment]
Just to add to this.  Even though CaDiCaL compiles on MacOs flawlessly (clang 14.0.3 with -std=c++11 and  with --pedantic even) the resource usage (also an issue with the windows port) is not correct, i.e., resident set size (both maximum and current).  This will need to be fixed too.

**Comment by a1880** [comment]
To compile CaDiCaL under MinGW, two lines have to be swapped in `resources.cpp`

```
#include <windows.h>

//  psapi.h included after windows.h for MinGW64

#include <psapi.h>

```

**Comment by arminbiere** [comment]
Thanks, just swapped the MinGW includes in 'resources.cpp' for release 1.7.1

**Comment by arminbiere** [comment]
Just a follow-up on this one.  It turns out that 'clang-format' sorts header include lines alphabetically (which I happened to have as coding style anyhow), but here the order is non-alphabetically. Therefore these two lines of includes have to be protected from clang-formatting, which was not there.  This was actually quite annoying since formatting is usually the last thing we do before a release (assuming it does not break things which it did here, i.e., the windows / mingw cross compilation did not work anymore).
