### ISSUE TITLE
Getting stuck on a cube in incremental mode (without logging)

### ISSUE THREAD

**Issue by jreeves3** [arminbiere/cadical#44]
With the attached incremental formula [bugInc.cnf.zip](https://github.com/arminbiere/cadical/files/8787034/bugInc.cnf.zip), if you run normal cadical (no `-l `flag for `configure`), you get stuck on cube 8262. But, if you configure with the `-l` flag, that cube is solved instantly. We expect the cube should be easy to solve, as it was in the ladder configuration.

**Comment by arminbiere** [comment]
Thanks, and sorry that it took me some time to confirm this.  The two versions with and without '-l' diverge in cube 1038 already (just use '-v -v -v' and diff the output).  My suspicion is that this is due garbage collection being triggered at different times with and without '-l'.  With '-l' the 64-bit clause ID is included in clauses which gives different memory usage with and without '-l' and thus also difference garbage collection time points.  As garbage collection might also result in different order of clauses in the arena, the non-deterministic effect we are seeing is probably due to that.  We have an internal version of CaDiCaL where we permanently have the clause id where this issue dissappears.  I plan to make it permanent by default already now.

**Comment by arminbiere** [comment]
BTW, the version with '-l' did not hang but was just unlucky to take 4000+ seconds to solve that cube.

**Comment by arminbiere** [comment]
Actually the culprit is to trigger garbage collection during variable elimination based on the number of garbage bytes in garbage clauses.  So an alternative to fix this would be to make this check dependent on the number of garbage clauses or just the total number of literals in garbage clauses.  However as we will need the ID in the future anyhow I will follow what I wrote before and just add ID all the time (wasting 8 bytes per clause).

**Comment by arminbiere** [comment]
Has been resolved in the 1.5.4-rc.1 release candidate.

**Comment by arminbiere** [comment]
This is now on the main branch and released (starting with 1.5.4).
