### ISSUE TITLE
What options might influence cadical's behaviour the most?

### ISSUE THREAD

**Issue by anwu1219** [arminbiere/cadical#53]
Dear Armin,

This is a similar question to [one](https://github.com/arminbiere/kissat/issues/25) in the kissat repo, regarding parameters of that are worth tuning. 

There you recommended to tune: "tier1/tier2, chrono, stable, walkinitially, target, phase,shrink"

I guess the equivalence of them in cadical are:
"reducetier{1/2}glue, chrono, stabilize, walk(?), target,phase,shrink"

My questions are:
1. Is this still a good set to tune? 
2. If I tune these options on cadical, will the effect mostly translate to kissat? (I realized this is a weird question, and please ignore if this is not the right place to ask it).

Thank you in advance!
Andrew

**Comment by arminbiere** [comment]
Yes, I would give a similar answer as for Kissat, but in general note that Kissat and CaDiCaL are by design trying many of these variances in an interleaved fashion.  For instance they switch between focused and stable phases and try to allocate the same amount of time (measured in ticks to keep things deterministic) for those two.  The stable mode is usually better for satisfiable problems and vice versa the focused mode for unsatisfiable.  But it is not always like that and the default of allocating half the time for each mode gives robust search behavior.  Nevertheless there are instances where 'stable' only is best and very few instances where it is the opposite (and focused mode only is best).  So if you start tuning options you are moving away from the test robust search behavior.  In my experience more often than not harmful instead of useful.

**Comment by anwu1219** [comment]
Hi Armin, I just saw your response. Thank you so much for the insightful answer.
