### ISSUE TITLE
Was 1.5.3 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [arminbiere/cadical#55]
The repo seems to think 1.5.3 came out in February but Homebrew already updated to that version in November last year. 
The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do so I want to make sure that this was intentional.

**Comment by arminbiere** [comment]
I know.  The reason for this insane tagging, was that the main branch version identifier '1.5.3' was frozen due to the SAT Competition organizers wanting to use it for the CaDiCaL track but some overdue documentation fixes still had to be added.    On the main branch there should not be any real difference in code to the older version.

**Comment by arminbiere** [comment]
We are in the process of merging two internal versions of CaDiCaL (user-propagation, LRAT support) and the development branch (CadiBack support, on-the-fly subsumption) all related to recently accepted papers, but that will keep us busy at least this month before we will get to 2.0.0.
