### ISSUE TITLE
radix.hpp doesn't compile on MacOS X.

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#7]
@arminbiere:

There are a few issues on MacOS X (using the default clang++ compiler
and libraries). 

This construct is not allowed:
```
v = new T [n];
b = I (v);
```
Here's the compilation error: 
```
../src/radix.hpp:90:11: error: calling a private constructor of class 'std::__1::__wrap_iter<CaDiCaL::Clause **>'
      b = I (v);
```

**Comment by arminbiere** [comment]
WIthout the context (what is 'I' here) it is hard to fix (without being able to run on MacOS).

**Comment by arminbiere** [comment]
After getting the osx partially working on travis I saw that my simple way of getting
an iterator from and array is not compatible with iterators from a vector with the same
element types.  So I added a vector instead of the explicit new which forced that for
temporary space.  This is guarded by a 'initialized' flag and using 'vector::reserve' should
also not be slower.  Tests pass ....
